### ISSUE TITLE
Installation error on Windows

### ISSUE THREAD

**Issue by cptolemy** [xoolive/traffic#111]
Hi

I'm not able to install **traffic** in my _Windows 64b, in Python36_ (works fine this version).  Here are the messages before the error code 1:
```
Collecting traffic
  Using cached https://files.pythonhosted.org/packages/89/9c/f9c93f5f85bf5e4a41db0a319ceb29b8e964e1feb027e5afb92fa45ae4ba/traffic-2.5-py3-none-any.whl
[truncated]
Collecting Cartopy (from traffic)
  Using cached https://files.pythonhosted.org/packages/46/c1/04e50c9986842f00f7db0e7a65caa896840050d7328f74e5b7437aa01179/Cartopy-0.18.0.tar.gz
    Complete output from command python setup.py egg_info:
    C:\Users\UTILIZ~1\AppData\Local\Temp\pip-build-wlwan6n3\Cartopy\setup.py:107: UserWarning: Unable to determine GEOS version. Ensure you have 3.3.3 or later installed, or installation may fail.
      '.'.join(str(v) for v in GEOS_MIN_VERSION), ))
    Proj 4.9.0 must be installed.

```

Any ideas? I have GEOS installed.

Best regards

Ptolemy

**Comment by xoolive** [comment]
Well the problem is obviously not with GEOS but with Proj as stated by the error message.

To avoid such troubles, I recommend in the installation to install shapely and cartopy through conda: they will come with the proper C dependencies attached. Look at the "warning" box here: https://traffic-viz.github.io/installation.html
