### ISSUE TITLE
NM B2B version 23.0.0 is deprecated, please update to 25.0.0

### ISSUE THREAD

**Issue by pontushed** [xoolive/traffic#182]
https://github.com/xoolive/traffic/blob/5784e96d538fa3e4acaa6ded1f373d1393067b83/traffic/data/__init__.py#L95

Hello Xavier,

Thanks for all the effort on this incredible library.

The default fallback version of the NM B2B is set to 23.0.0. However, this version is about to cease functioning soon. As from Eurocontrol:

_This version (NM23.0) is currently the deprecated version._

This means that IT WILL NO LONGER BE AVAILABLE AFTER NM26.0 MIGRATION currently planned:
- For PRE-OPS on the 29/03/2022 -> NM23.0 PREOPS will no longer be available after this date,
- For OPS on the 26/04/2022 -> NM23.0 OPS will no longer be available after this date.
Please therefore take the necessary actions to migrate your NM B2B Web Services to NM25.0 version.

I propose that you change the fallback version to 25.0.0 for future compatibility and add a mention in the documentation about the version switch option in the configuration file.

**Comment by xoolive** [comment]
Thank you @pontushed for the info. I updated the default version where you mentioned (so you can remove the item in your configuration file)

Please don't hesitate to suggest modifications as pull requests in the future. I cover only a small subset of B2B here because I don't need more, but I am open to include more if people need it!
