### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by EmpAk** [xoolive/traffic#54]
Error downloading a large chunk of data:
>   File "pandas/_libs/parsers.pyx", line 2172, in pandas._libs.parsers.raise_parser_error
> 
> ParserError: Error tokenizing data. C error: Expected 17 fields in line 23725, saw 31

thrown by
>   File "C:\Users\olsc\AppData\Local\Continuum\anaconda3\lib\site-packages\traffic\data\adsb\opensky_impala.py", line 115, in _read_cache
>     df = pd.read_csv(s, dtype={"icao24": str, "callsign": str})

example (error occurs after a few minutes): 
```
data_raw = opensky.history(
    "2018-01-01 00:01",
    "2018-02-01 00:00",
    bounds=(
        7.99182, 47.09367, #sw
        9.24188, 47.83655 #ne
    ),
)  
```

Adding error_bad_lines=False or engine='python' to read_csv did not help.

Any way to skip these erroneous lines?
(Interestingly enough, putting the start time at hour 00:00 yields a different error.)

**Comment by xoolive** [comment]
Hello @EmpAk 

Indeed, this sometimes happens when dumping data from the shell to a file, and lines from the request get mixed with the result. It happens less now after a small fix in the way requests are handled, but the problem has not disappeared.

The problem now is that when you launch the script again, it takes the same cached request and tries to read it.

For now, here are two options to get around this:
- add the `cached=False` option to `opensky.history` (it will download everything again)
- activate the INFO logs to see the path to the cached file (there you can check line 23725 and see what went wrong...) and manually remove only this file.
  ```python
	import logging
	logger = logging.getLogger()
	# this activates INFO logging messages
	logger.setLevel(logging.INFO)
  ```

By the way, since you are downloading a large interval (one month) I would recommend you adjust the `date_delta` parameter to something between `timedelta(hours=6)` and `timedelta(days=1)`. You must now see a progressbar of ~600 iterations (hence 600 requests). Usually, the default `timedelta(hours=1)` is a good rule of a thumb, but if the area you are considering is smaller, you can better calibrate it.

I will keep the issue open until I update the script to remove cache files when this error happens.

**Comment by xoolive** [comment]
The hereabove commit provides more insight into the error and will automatically remove the faulty cache file. Would you try this version and re-open the issue if the behaviour is still unacceptable?
