### ISSUE TITLE
traffic.opensky returns None

### ISSUE THREAD

**Issue by simonrp84** [xoolive/traffic#76]
Hi Xavier,
I'm trying to download some icao24-specific flights from opensky, but get Nonetype as a return.
My code, with the specific icao24 code removed here:
```
ic24 = 'icao_removed'
start_dt = datetime(2020, 2, 23, 18, 30, tzinfo = pytz.utc)
end_dt = datetime(2020, 2, 23, 18, 50, tzinfo = pytz.utc)
flights = opensky.history(start=start_dt, stop=end_dt, icao24=ic24)
print(type(flights))
```

My debug:
```
INFO:root:Sending request between time 2020-02-23 18:30:00+00:00 and 2020-02-23 18:50:00+00:00 and hour 2020-02-23 18:00:00+00:00 and 2020-02-23 19:00:00+00:00
INFO:root:Sending request: select time, icao24, lat, lon, velocity, heading, vertrate, callsign, onground, alert, spi, squawk, baroaltitude, geoaltitude, lastposupdate, lastcontact, hour from state_vectors_data4  where hour>=1582480800.0 and hour<1582484400.0 and time>=1582482600.0 and time<1582483800.0 and icao24='icao_removed' 
```

The `print` output: ```<class 'NoneType'>```
If I log in to the opensky impala shell via ssh and run the `select` request shown in the debug prompt above then I do receive the data. It just doesn't seem to get parsed properly in `traffic`. In case it is important, a cache file is produced with size 141kb

Any idea what the problem might be?

**Comment by xoolive** [comment]
Returning `None` means usually there is no parsable data in the cache file.

First option: add the `cached=False` option to try to download again. Shit happens...

Second option: have a look at the cache file. If you can't see what's wrong, send me a link to download it or just attach it to an email if it's not too big.

**Comment by simonrp84** [comment]
Sorry, I should have said. I manually deleted the cache and tried again, same result.
If I try opening the cache with `Traffic.from_file()` then I also get `None`. I've attached the cache file here, zipped to keep github happy, hopefully you can see what's happened :)
[646397b86cb843db320819eeb8d79a1b.zip](https://github.com/xoolive/traffic/files/4252132/646397b86cb843db320819eeb8d79a1b.zip)

**Comment by xoolive** [comment]
The data you sent is full of NULL values for positions.

`opensky.history` returns state vectors which are not real ADS-B reports. Impala stores different types of messages on separate tables and artificially reconstructs state vectors. It is still not clear to me whether the state vectors are supposed to include aircraft with ADS-B non compliant transponders.

There are indeed Enhanced Mode S reports but these are sent by most aircraft equipped with a transponder, even if it is not ADS-B compliant.

Long story short: since your aircraft has no position reports, the `last_position` column is all `NaT` so all the lines are filtered out by the following line:

https://github.com/xoolive/traffic/blob/a878ba5403c3c4efeebe76db38d0c74d8c1f3a07/traffic/data/adsb/opensky_impala.py#L875

This line has been very helpful in the past to avoid empty trajectories which would cause a mess.

In the end, it all boils down to: should `opensky.history` return empty trajectories at the risk of leaving more mess handling to the user, or should we consider it returns only information from ADS-B. I have not made my mind yet. Your opinion is welcome.

**Comment by simonrp84** [comment]
Yes, I had not noticed that all the position data was null in the impala dataset.
I think that the current implementation of `last_position` on line 875 is the best choice, although it could be useful to add a warning (maybe only if the user searches by `icao24`) in the case that an aircraft has no valid position data.

**Comment by xoolive** [comment]
Is it clear in your mind when to put a warning and when not? I wouldn't want to send zillions of warning each time something is filtered...

If you do, as you know, I always welcome PR 😉

**Comment by simonrp84** [comment]
That's the thing - it's difficult to decide when to warn and when not.
I will have a think, and if I come up with anything sensible I will indeed make a PR :)
Thanks for your help, I'll close this now.
