### ISSUE TITLE
Retrieving list of sensors that 'saw' aircraft

### ISSUE THREAD

**Issue by simonrp84** [xoolive/traffic#86]
Hello,
I noticed in the Opensky Impala guide that many of the datasets have a `serials` or similar column that contains an array of all sensor serials that saw a given aircraft message.
Is it possible to retrieve this list of serials using `traffic`? I can see that it's possible to query opensky via the serial, but can't see how to retrieve this as a column in the downloaded data.
Thanks!

**Comment by xoolive** [comment]
Hello @simonrp84 

In theory, it is possible to pass any query with `opensky.request`, so the answer is yes of course :)

Actually the query with `history` would be:
```python
opensky.history(
	**same_same,
    other_tables=", state_vectors_data4.serials s",
    other_columns=", s.ITEM"
)
```
**but** `other_columns` is not available yet 😆 , so you may want to try something along:

```python
opensky.request(
	"""select *, s.ITEM from s, state_vectors_data4.serials s 
	   where hour>={before_hour} and hour<{after_hour}
	   and time>={before_time} and time<{after_time}""",
    "2020-01-01",
    "2020-01-02",
    columns=["p1", "p2", etc.]
)
```

**However**, the thing with the serials is that they are defined as an array, and the SQL output expands these arrays. So basically, if you see an aircraft at one position through 36 sensors, you must download the same line 36 times... not sexy, uh?

For debugging purposes, I recently implemented [`Flight.query_opensky_sensors()`](https://github.com/xoolive/traffic/blob/364dd92f869ffd9b49c767bf52f00e672256a81d/traffic/core/flight.py#L1632) (not yet documented because I am thinking I should find a better name for the method...) which yields a table with sensor id and number of messages.

You can of course chain it like:
```python
flight.first('1H').query('altitude < 5000').query_opensky_sensors()
```

You probably need the `HEAD` version on `master`.

I hope this answers most of your questions. If you really need the `other_columns` parameter, I can find time for that (or you can give it a shot 😉)

**Comment by xoolive** [comment]
Hello @simonrp84 I will close the issue, don't hesitate to reopen if this does not work.

**Comment by simonrp84** [comment]
Aaah, so sorry Xavier - I thought I'd already replied to this. Yes this does what I need, thanks very much!
