### ISSUE TITLE
Track angle values after leaving runway (onto taxiway)

### ISSUE THREAD

**Issue by TheYsconator** [xoolive/traffic#91]
It appears as though the track values (in .data) stay the same after leaving the runway. Do you know if that is intended? If I wanted to get (or estimate) those track values (or the heading values), would then the best way be to determine those off the lat/long/time?

More in detail, explained with the belevingsvlucht:

```
flight = belevingsvlucht

# The piece of flight near the end of the flight: the first part is on the runway, and it ends on a taxiway.
flight = flight.between("2018-05-30 20:18:09", "2018-05-30 20:19:57")

# This retrieves the name of last row which is still on the runway.
flight.on_runway(airport).at_ratio(1).name

# The last point on the runway has name '15767'. The following line shows the 10 rows before and after that datapoint.
flight.data.iloc[38 : 58]
```

All 'track' values are 58, even the ones that are no longer on the runway. I checked by going back to belevingsvlucht and looking at the track values of the last datapoints (using belevingsvlucht.last("20s").data), which are also all 58.

**Comment by xoolive** [comment]
Hello Ysbrand,

Indeed, this kind of 💩 happens...

Basically, when you look at the state vectors table, you get information merged from various types of ADS-B messages (check details [here](https://mode-s.org/)): one of these messages contains the track angle. Then the state vectors table writes a new line each time it sees a new message and updates only the information contained in the message. So here, I guess the network got messages, but none of the type containing the track angle values, then it propagated the latest known value of track angles.

You can check the implementation of `Flight.cumulative_distance()` where we get to recompute a ground speed (called then `compute_gs`). I guess you can add an argument `compute_track` and use `geo.bearing` instead of `geo.distance` if you want to implement the track value estimation.

If you take time to write an implementation (it is really easy), I would be glad to accept a PR. 😄 

Last, be careful and talk about true track angles not magnetic heading: even on ground, `track != heading` because of [magnetic declination](https://traffic-viz.github.io/scenarios/geomagnetic_declination.html).

**Comment by TheYsconator** [comment]
Hey Xavier! Thank you for always replying so swiftly. I didn't get to implementing this last week, but I did manage to make a stub and look into track, heading and magnetic declination. I'll make a PR when I think the implementation is complete.

(Leaving this open for now, in case I have a follow-up question. Will close once PR is made.)

**Comment by TheYsconator** [comment]
Continued in #93.
